name: transcript-summarizer
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - numpy==1.23.3
    - streamlit
    - openai-whisper
    - whisper
    - requests
    - numba
    - torch
    - tqdm
    - more-itertools
    - tiktoken
    - ffmpeg-python
  - ffmpeg
